apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /run/desktop/mnt/host/c/Users/hi/Downloads/hsho/STUDY_FILES-docker/practice39(2.26)/mariadb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
