apiVersion: v1
kind: Pod
metadata:
  name: local-disk-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx:1.28
      ports:
      - containerPort: 80
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: local-vol
  volumes:
    - name: local-vol
      hostPath:
        path: /run/desktop/mnt/host/c/Users/hi/Downloads/hsho/STUDY_FILES-docker/practice39(2.26)/html #C:/
        type: DirectoryOrCreate
---
apiVersion: v1
kind: Service

metadata:
  name: local-disk-service

spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
