FROM python:3.13.11 as build

RUN apt-get update
RUN apt-get upgrade -y
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
RUN pip install uv

WORKDIR /workspace

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-dev

COPY ./app .

FROM python:3.13.11

WORKDIR /workspace

COPY --from=build /workspace/.venv /workspace/.venv
COPY --from=build /workspace/app /workspace/app

ENV PATH="/workspace/.venv/bin:$PATH"

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
