apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /run/desktop/mnt/host/c/IDE/workspaces/STUDY_FILES/study39/html
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
